@startuml
!define C4PLANTUML https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include DEVICONS/msql_server.puml
!include C4PLANTUML/C4_Container.puml
!include C4PLANTUML/C4.puml
!include C4PLANTUML/C4_Context.puml
!include C4PLANTUML/C4_Component.puml
!include DEVICONS2/angularjs.puml
!include DEVICONS2/dot_net.puml
!include DEVICONS2/java.puml
!include DEVICONS2/cplusplus_line.puml

!include FONTAWESOME/server.puml
!include FONTAWESOME/envelope.puml
!include DEVICONS2/react_original.puml
!include DEVICONS2/postgresql.puml
!include DEVICONS2/docker_wordmark.puml
!include DEVICONS2/redis.puml
@enduml
