@startuml

'******* AAVA Styles *************
' HEADER
header '<img:https://www.aava.fi/sites/default/files/field_data/page/Aava_pystylogo_cmyk.jpg{scale=0.1}>

' TITLE STYLES
skinparam TitleFontSize 30
skinparam TitleFontColor #1f9ad7

' SWIMLANE STYLES
skinparam SwimlaneTitleFontSize 20
skinparam SwimlaneTitleBackgroundColor #1f9ad7
skinparam SwimlaneTitleFontColor white
skinparam SwimlaneBorderThickness 1

' ACTIVITY STYLES
skinparam ActivityBorderColor black
skinparam ActivityBackgroundColor #c7e7f4
skinparam ActivityDiamondBackgroundColor #e9f4d4
skinparam ActivityDiamondBorderColor black

'COMMON STYLES
skinparam ArrowColor #1f9ad7
skinparam Shadowing false
skinparam NoteBackgroundColor white
skinparam NoteBorderColor black

@enduml
