@startuml

'******* AAVA Styles *************
' HEADER
header '<img:https://www.aava.fi/sites/default/files/field_data/page/Aava_pystylogo_cmyk.jpg{scale=0.1}>

' TITLE STYLES
skinparam TitleFontSize 30
skinparam TitleFontColor #1f9ad7

' SWIMLANE STYLES
skinparam SwimlaneTitleFontSize 20
skinparam SwimlaneTitleBackgroundColor #1f9ad7
skinparam SwimlaneTitleFontColor white
skinparam SwimlaneBorderThickness 1

' ACTIVITY STYLES
skinparam ActivityBorderColor black
skinparam ActivityBackgroundColor #c7e7f4
skinparam ActivityDiamondBackgroundColor #e9f4d4
skinparam ActivityDiamondBorderColor black

'SEQUENCE STYLES
skinparam actorStyle awesome
skinparam ActorBackgroundColor #93d4f1
skinparam ActorBorderColor #239ed5
skinparam ParticipantBackgroundColor #93d4f1
skinparam ParticipantBorderColor #239ed5
skinparam SequenceLifeLineBorderColor black

'DATAMODEL
!define table(x) class x << (T,#239ed5) >> 
!define view(x) class x << (V,#93d4f1) >>
skinparam classarrowcolor gray
skinparam ClassBackgroundColor white
skinparam ClassBorderColor black

' usage:
'  table(example) {
'       id: int <<pk>>
'       column1: char 11
'}

'COMMON STYLES
skinparam ArrowColor #1f9ad7
skinparam Shadowing false
skinparam NoteBackgroundColor white
skinparam NoteBorderColor black

@enduml
