@startuml

'******* AAVA Styles *************
' AAVA COLORS
!define sininen 239ed5
!define vaaleansininen 93d4f1
!define haaleasininen c7e7f4
!define vihrea 9fcd40
!define vaaleanvihrea d8e8af
!define haaleavihrea e9f4d4
!define lila c53196
!define vaalealila e7abd3
!define haalealila f0cae4

' HEADER
header '<img:https://www.aava.fi/sites/default/files/field_data/page/Aava_pystylogo_cmyk.jpg{scale=0.1}>

' TITLE STYLES
skinparam TitleFontSize 30
skinparam TitleFontColor #sininen

' SWIMLANE STYLES
skinparam SwimlaneTitleFontSize 20
skinparam SwimlaneTitleBackgroundColor #sininen
skinparam SwimlaneTitleFontColor white
skinparam SwimlaneBorderThickness 1

' ACTIVITY STYLES
skinparam ActivityBorderColor black
skinparam ActivityBackgroundColor #haaleasininen
skinparam ActivityDiamondBackgroundColor #haaleavihrea
skinparam ActivityDiamondBorderColor black

'SEQUENCE STYLES
skinparam actorStyle awesome
skinparam ActorBackgroundColor #vaaleansininen
skinparam ActorBorderColor #sininen
skinparam ParticipantBackgroundColor #vaaleansininen
skinparam ParticipantBorderColor #sininen
skinparam SequenceLifeLineBorderColor black

'DATAMODEL
!define table(x) class x << (T,#sininen) >> 
!define view(x) class x << (V,#vaaleansininen) >>
skinparam classarrowcolor gray
skinparam ClassBackgroundColor white
skinparam ClassBorderColor black

' usage:
'  table(example) {
'       id: int <<pk>>
'       column1: char 11
'}

'COMMON STYLES
skinparam ArrowColor #sininen
skinparam Shadowing false
skinparam NoteBackgroundColor white
skinparam NoteBorderColor black

@enduml
